spring:
  datasource:
    url: ${DB_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    hikari:
      connection-timeout: 10000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 2 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 5 #maximum pool size
      idle-timeout: 300000 #maximum idle time for connection
      max-lifetime: 1800000 #maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jackson:
    serialization:
      write-dates-as-timestamps: true

  flyway:
    url: ${DB_URL}
    user: ${PG_USER}
    password: ${PG_PASSWORD}
    enabled: true
    locations: classpath:db/migration

server:
  servlet:
    context-path: /api/v1
